version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  veiculos-service:
    build:
      context: .
      dockerfile: veiculos-service/Dockerfile
    container_name: veiculos-service
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092

  motoristas-service:
    build:
      context: .
      dockerfile: motoristas-service/Dockerfile
    container_name: motoristas-service
    ports:
      - "8081:8081"
    depends_on:
      - kafka

  abastecimentos-service:
    build:
      context: .
      dockerfile: abastecimentos-service/Dockerfile
    container_name: abastecimentos-service
    ports:
      - "8082:8082"
    depends_on:
      - veiculos-service
      - motoristas-service
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      # Define as URLs para a comunicação interna do Docker
      - URL_VEICULOS=http://veiculos-service:8080
      - URL_MOTORISTAS=http://motoristas-service:8081